### ISSUE TITLE
[Feedback]: macOS recommended way to reload netdata configuration

### ISSUE THREAD

**Issue by jhgorse** [netdata/learn#1637] opened 2023-05-10 01:27 UTC
### Doc Page link

https://learn.netdata.cloud/docs/installation/install-on-specific-environments/macos#install-netdata-with-our-automatic-one-line-installation-script

### Description

What is the recommended way to reload netdata configuration on macOS? Using the `launchctl load /Library/LaunchDaemons/com.github.netdata.plist` always spawns two netdata processes while `unload` does not stop them. `start/stop` have no effect.

So then what is the recommended way to reload configuration on macOS? And please don't tell me to reboot the computer. =)

Cheers

**Comment by Ancairon** [comment] 2023-09-27 07:15
Hey @jhgorse this seems like a duplicate of https://github.com/netdata/netdata/issues/13829 and https://github.com/netdata/netdata/issues/12578, so I am closing this issue, and going to bring the matter up internally.

**Closed by Ancairon** 2023-09-27 07:15 UTC
Labels: feedback
